version: 1
kind: Document

metadata:
  name: Customers
  description: Information about each customer is saved here
  authors:
    - name: James Brown
      email: james@brown.com

data_fetch_workflow: # The workflow for fetching source data. Workflows like are hidden by default.
  name: Fetch Active Campaign Email Subscribers
  id: 2f5d951c-dd3c-4f87-a790-0f8fb78fc405 # database id
  specification_file_url: www.gigamono.com/project/3jOApF4U10rBe0LL4ekuUA/workflow.VvahTjdfR1O7h_KtP_0yZA.ul9CkhJsSAKdiOXwjpX5SA.json
  inputs: # Calls the workflow like a function.
    offset: "{{tableVariables().offset}}"
    limit: "{{tableVariables().limit}}"

schema:
    - name: Name
      kind: single_line_text
    - name: Available Products
      kind: relationship

views:
    table:
      grouped_by:
        - state
        - county
      filtered_by:
        - op: contains
          field: name
          rhs: james
      sorted_by:
        - field: name
          order: ascending
      hidden_fields:
        - updated_at
        - created_at
        - modified_at
      layout:
        row_height: short

    board:
      stacked_by: state
      filtered_by:
        - op: contains
          field: name
          rhs: james
      sorted_by:
        - field: name
          order: ascending
      hidden_fields:
        - updated_at
        - created_at
        - modified_at

