version: 1
kind: Table

metadata:
  name: Products
  description: Information about each my customers
  column_name_convention: lower_snake_case_plural
  authors:
    - name: James Brown
      email: james@brown.com

data_fetch_workflow: # The workflow for fetching source data. Workflows like this are hidden by default.
  name: Fetch Active Campaign Email Subscribers
  id: 2f5d951c-dd3c-4f87-a790-0f8fb78fc405 # database id
  specification_file_url: www.gigamono.com/project/3jOApF4U10rBe0LL4ekuUA/workflow.VvahTjdfR1O7h_KtP_0yZA.ul9CkhJsSAKdiOXwjpX5SA.json
  inputs: # Calls the workflow like a function.
    offset: "{{tableVariables().offset}}"
    limit: "{{tableVariables().limit}}"

database_workflow:
  name: PostgreSQL
  id: 2f5d951c-dd3c-4f87-a790-0f8fb78fc405 # database id
  specification_file_url: www.gigamono.com/project/3jOApF4U10rBe0LL4ekuUA/workflow.VvahTjdfR1O7h_KtP_0yZA.ul9CkhJsSAKdiOXwjpX5SA.json
  inputs:
    uri: "{{tableVariables().URI}}"


schema: # The current schema
    max: 13
    items:
      10:
        name: Name
        order: 0
        kind: text

      11:
        name: State
        order: 1
        kind: select
        dropdown:
          allows_multiple: false
          options:
            max: 2
            items:
              0:
                name: CA
                order: 0
              1:
                name: WA
                order: 1

      12:
        name: County
        kind: text

      13:
        name: Liked Products
        kind: relationship
        linked_table:
          id: 24f495c3-7fc6-4bea-bf7a-adb0a955a54f
          specification_file_url: www.gigamono.com/project/3jOApF4U10rBe0LL4ekuUA/integration.VvahTjdfR1O7h_KtP_0yZA.ul9CkhJsSAKdiOXwjpX5SA.json
          field: 10


views:
    max: 1
    items:
      0:
        kind: table
        name: Customers by State and County
        order: 0
        grouped_by:
          - 11 # state
          - 12 # county
        filtered_by:
          - op: contains
            field: 10 # name
            rhs: james
        sorted_by:
          - field: 10 # name
            order: ascending
        hidden_fields:
          - 1 # created_at
          - 2 # updated_at
          - 3 # deleted_at
        layout:
          row_height: short

      1:
        kind: board
        order: 1
        name: Customers by State
        stacked_by: 11 # state
        filtered_by:
          - op: contains
            field: 10 # name
            rhs: james
        sorted_by:
          - field: 10 # name
            order: ascending
        hidden_fields:
          - 1 # created_at
          - 2 # updated_at
          - 3 # deleted_at


migrations:
  "2021_03_31.07_10_10":
    kind: add_column
