version: 1
kind: Workflow

metadata:
  workflow_name: TeamCliff > Sorbel
  description: Lorem ipsum dolor sit amet
  authors:
    - name: James Brown
      contact: james@brown.com

tasks:
  - app_name: TeamCliff
    app_id: 7Gfh5n3r2jV6KLvfg9mJGtwUji8v370hwgT
    account_id: 6sTtscfdRyHEj77vh5SCtVSTJ6J7I8g7v6
    task_kind: trigger
    task_name: teamcliff
    task_index: 0
    dependencies: null
    position: [200, 150]
    fields:
      email: james@brown.com
      name: James Brown

  - app_name: Sorbel
    app_id: dEH3y6u7Bdt6vgh8t6e3yGBJmggJWl
    account_id: hduTJetECrh6J2738TV6ssyt783nou
    task_kind: action
    task_name: sorbel
    task_index: 1
    dependencies: [0] # Task 0 depends on Task 1
    position: [400, 150]
    fields:
      email: "$(tasks[0].fields.email)" # reference by task index
      name: "$(tasks.sorbel.fields.email)" # reference by task name
